name: Publish

on:
  workflow_dispatch: { }
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Configure GPG Key
        run: |
          echo '${{secrets.GPG_KEY_CONTENTS}}' | base64 -d > publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" --output secret.gpg publish_key.gpg

      - name: Publish to MavenCentral
        id: central
        run: ./gradlew test publishToSonatype --no-daemon --no-parallel -Psigning.secretKeyRingFile=secret.gpg -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Create release
        if: steps.central.outcome == 'success'
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/build/libs/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
